# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Map Update - Final - Prod.py
# Created on: 2013-08-22 07:04:49.00000
#   (generated by ArcGIS/ModelBuilder and modified by Eric Mahaffey w/Zekiah Technologies, Inc.)
# Description: 
# ---------------------------------------------------------------------------

import arcpy
import subprocess
import os
import time
import sys
import shutil

arcpy.env.overwriteOutput = 1

# Local variables:
Navteq_Cities_Composite = "D:\\Users\\Tools\\Geocoders\\NavteqCities"
FEMA_Regions_WGS84_Tribal_Overlap_Clip_20130402 = "D:\\Users\\Products\\PSA Map Updates\\Data\\Updates_20130401\\Regions and Districts Modified by Tribal.gdb\\FEMA_Regions_WGS84_Tribal_Overlap_Clip_20130402"
input_table = r"D:\Users\Products\PSA Map Updates\Automation\for ESRI Presentation\Data\Master List xls - modforpresentation.xlsx\'List - Outside Distro$'"
Tables_gdb = r"D:\Users\Products\PSA Map Updates\Automation\for ESRI Presentation\Data\Tables.gdb"
PSA_List_TableSelect = "D:\\Users\\Products\\PSA Map Updates\\Automation\\for ESRI Presentation\\Data\\Tables.gdb\\PSA_List_TableSelect"
PSA_List_TableSelect__5_ = "D:\\Users\\Products\\PSA Map Updates\\Automation\\for ESRI Presentation\\Data\\Tables.gdb\\PSA_List_TableSelect"
PSAs_and_RDs = "D:\\Users\\Products\\PSA Map Updates\\Automation\\for ESRI Presentation\\Data\\Features.gdb\\PSAs_and_RDs"
PSAs_and_RDs_SpatialJoin = "D:\\Users\\Products\\PSA Map Updates\\Automation\\for ESRI Presentation\\Data\\Features.gdb\\PSAs_and_RDs_SpatialJoin"
PSAs_and_RDs_SpatialJoin__4_ = "D:\\Users\\Products\\PSA Map Updates\\Automation\\for ESRI Presentation\\Data\\Features.gdb\\PSAs_and_RDs_SpatialJoin"
Output_Table = "D:\\Users\\Products\\PSA Map Updates\\Automation\\for ESRI Presentation\\Data\\Tables.gdb\\PSA_List"
PSAs_and_RDs_SpatialJoin__2_ = "D:\\Users\\Products\\PSA Map Updates\\Automation\\for ESRI Presentation\\Data\\Features.gdb\\PSAs_and_RDs_SpatialJoin"

# Process: Table to Table
tempEnvironment0 = arcpy.env.newPrecision
arcpy.env.newPrecision = "SINGLE"
tempEnvironment1 = arcpy.env.autoCommit
arcpy.env.autoCommit = "1000"
tempEnvironment2 = arcpy.env.XYResolution
arcpy.env.XYResolution = ""
tempEnvironment3 = arcpy.env.XYDomain
arcpy.env.XYDomain = ""
tempEnvironment4 = arcpy.env.scratchWorkspace
arcpy.env.scratchWorkspace = ""
tempEnvironment5 = arcpy.env.cartographicPartitions
arcpy.env.cartographicPartitions = ""
tempEnvironment6 = arcpy.env.terrainMemoryUsage
arcpy.env.terrainMemoryUsage = "false"
tempEnvironment7 = arcpy.env.MTolerance
arcpy.env.MTolerance = ""
tempEnvironment8 = arcpy.env.compression
arcpy.env.compression = "LZ77"
tempEnvironment9 = arcpy.env.coincidentPoints
arcpy.env.coincidentPoints = "MEAN"
tempEnvironment10 = arcpy.env.randomGenerator
arcpy.env.randomGenerator = "0 ACM599"
tempEnvironment11 = arcpy.env.outputCoordinateSystem
arcpy.env.outputCoordinateSystem = ""
tempEnvironment12 = arcpy.env.rasterStatistics
arcpy.env.rasterStatistics = "STATISTICS 1 1"
tempEnvironment13 = arcpy.env.ZDomain
arcpy.env.ZDomain = ""
tempEnvironment14 = arcpy.env.transferDomains
arcpy.env.transferDomains = "false"
tempEnvironment15 = arcpy.env.resamplingMethod
arcpy.env.resamplingMethod = "NEAREST"
tempEnvironment16 = arcpy.env.snapRaster
arcpy.env.snapRaster = ""
tempEnvironment17 = arcpy.env.projectCompare
arcpy.env.projectCompare = "NONE"
tempEnvironment18 = arcpy.env.cartographicCoordinateSystem
arcpy.env.cartographicCoordinateSystem = ""
tempEnvironment19 = arcpy.env.configKeyword
arcpy.env.configKeyword = ""
tempEnvironment20 = arcpy.env.outputZFlag
arcpy.env.outputZFlag = "Same As Input"
tempEnvironment21 = arcpy.env.qualifiedFieldNames
arcpy.env.qualifiedFieldNames = "true"
tempEnvironment22 = arcpy.env.tileSize
arcpy.env.tileSize = "128 128"
tempEnvironment23 = arcpy.env.parallelProcessingFactor
arcpy.env.parallelProcessingFactor = ""
tempEnvironment24 = arcpy.env.pyramid
arcpy.env.pyramid = "PYRAMIDS -1 NEAREST DEFAULT 75 NO_SKIP"
tempEnvironment25 = arcpy.env.referenceScale
arcpy.env.referenceScale = ""
tempEnvironment26 = arcpy.env.extent
arcpy.env.extent = "DEFAULT"
tempEnvironment27 = arcpy.env.XYTolerance
arcpy.env.XYTolerance = ""
tempEnvironment28 = arcpy.env.tinSaveVersion
arcpy.env.tinSaveVersion = "CURRENT"
tempEnvironment29 = arcpy.env.nodata
arcpy.env.nodata = "NONE"
tempEnvironment30 = arcpy.env.MDomain
arcpy.env.MDomain = ""
tempEnvironment31 = arcpy.env.spatialGrid1
arcpy.env.spatialGrid1 = "0"
tempEnvironment32 = arcpy.env.cellSize
arcpy.env.cellSize = "MAXOF"
tempEnvironment33 = arcpy.env.outputZValue
arcpy.env.outputZValue = ""
tempEnvironment34 = arcpy.env.outputMFlag
arcpy.env.outputMFlag = "Same As Input"
tempEnvironment35 = arcpy.env.geographicTransformations
arcpy.env.geographicTransformations = ""
tempEnvironment36 = arcpy.env.spatialGrid2
arcpy.env.spatialGrid2 = "0"
tempEnvironment37 = arcpy.env.ZResolution
arcpy.env.ZResolution = ""
tempEnvironment38 = arcpy.env.mask
arcpy.env.mask = ""
tempEnvironment39 = arcpy.env.spatialGrid3
arcpy.env.spatialGrid3 = "0"
tempEnvironment40 = arcpy.env.maintainSpatialIndex
arcpy.env.maintainSpatialIndex = "false"
tempEnvironment41 = arcpy.env.workspace
arcpy.env.workspace = ""
tempEnvironment42 = arcpy.env.MResolution
arcpy.env.MResolution = ""
tempEnvironment43 = arcpy.env.derivedPrecision
arcpy.env.derivedPrecision = "HIGHEST"
tempEnvironment44 = arcpy.env.ZTolerance
arcpy.env.ZTolerance = ""
arcpy.TableToTable_conversion(input_table, Tables_gdb, "PSA_List", "", "NAME \"NAME\" true true false 255 Text 0 0 ,First,#,D:\\Users\\Products\\PSA Map Updates\\Automation\\for ESRI Presentation\\Source Tables\\Master List xls - modforpresentation.xlsx\\'List - Outside Distro$',Personnel Master List,-1,-1;CITY \"DISTRICT\" true true false 255 Text 0 0 ,First,#,D:\\Users\\Products\\PSA Map Updates\\Automation\\for ESRI Presentation\\Source Tables\\Master List xls - modforpresentation.xlsx\\'List - Outside Distro$',F3,-1,-1;STATE \"STATE\" true true false 255 Text 0 0 ,First,#,D:\\Users\\Products\\PSA Map Updates\\Automation\\for ESRI Presentation\\Source Tables\\Master List xls - modforpresentation.xlsx\\'List - Outside Distro$',F4,-1,-1", "")
#arcpy.TableToTable_conversion(input_table, Tables_gdb, "PSA_List", "", "NAME \"NAME\" true true false 50 Text 0 0 ,First,#,D:\\Users\\Products\\PSA Map Updates\\Automation\\for ESRI Presentation\\Source Tables\\Master List xls - modforpresentation.xlsx\\'PSA List - Outside Distro$',Personnel Master List,-1,-1;CITY \"F3\" true true false 50 Text 0 0 ,First,#,D:\\Users\\Products\\PSA Map Updates\\Automation\\for ESRI Presentation\\Source Tables\\Master List xls - modforpresentation.xlsx\\'PSA List - Outside Distro$',F3,-1,-1;STATE \"F4\" true true false 50 Text 0 0 ,First,#,D:\\Users\\Products\\PSA Map Updates\\Automation\\for ESRI Presentation\\Source Tables\\Master List xls - modforpresentation.xlsx\\'PSA List - Outside Distro$',F4,-1,-1;PHONE_OFFICE \"F5\" true true false 20 Text 0 0 ,First,#,D:\\Users\\Products\\PSA Map Updates\\Automation\\for ESRI Presentation\\Source Tables\\Master List xls - modforpresentation.xlsx\\'PSA List - Outside Distro$',F5,-1,-1;PHONE_MOBILE \"F6\" true true false 20 Text 0 0 ,First,#,D:\\Users\\Products\\PSA Map Updates\\Automation\\for ESRI Presentation\\Source Tables\\Master List xls - modforpresentation.xlsx\\'PSA List - Outside Distro$',F6,-1,-1", "")
arcpy.env.newPrecision = tempEnvironment0
arcpy.env.autoCommit = tempEnvironment1
arcpy.env.XYResolution = tempEnvironment2
arcpy.env.XYDomain = tempEnvironment3
arcpy.env.scratchWorkspace = tempEnvironment4
arcpy.env.cartographicPartitions = tempEnvironment5
arcpy.env.terrainMemoryUsage = tempEnvironment6
arcpy.env.MTolerance = tempEnvironment7
arcpy.env.compression = tempEnvironment8
arcpy.env.coincidentPoints = tempEnvironment9
arcpy.env.randomGenerator = tempEnvironment10
arcpy.env.outputCoordinateSystem = tempEnvironment11
arcpy.env.rasterStatistics = tempEnvironment12
arcpy.env.ZDomain = tempEnvironment13
arcpy.env.transferDomains = tempEnvironment14
arcpy.env.resamplingMethod = tempEnvironment15
arcpy.env.snapRaster = tempEnvironment16
arcpy.env.projectCompare = tempEnvironment17
arcpy.env.cartographicCoordinateSystem = tempEnvironment18
arcpy.env.configKeyword = tempEnvironment19
arcpy.env.outputZFlag = tempEnvironment20
arcpy.env.qualifiedFieldNames = tempEnvironment21
arcpy.env.tileSize = tempEnvironment22
arcpy.env.parallelProcessingFactor = tempEnvironment23
arcpy.env.pyramid = tempEnvironment24
arcpy.env.referenceScale = tempEnvironment25
arcpy.env.extent = tempEnvironment26
arcpy.env.XYTolerance = tempEnvironment27
arcpy.env.tinSaveVersion = tempEnvironment28
arcpy.env.nodata = tempEnvironment29
arcpy.env.MDomain = tempEnvironment30
arcpy.env.spatialGrid1 = tempEnvironment31
arcpy.env.cellSize = tempEnvironment32
arcpy.env.outputZValue = tempEnvironment33
arcpy.env.outputMFlag = tempEnvironment34
arcpy.env.geographicTransformations = tempEnvironment35
arcpy.env.spatialGrid2 = tempEnvironment36
arcpy.env.ZResolution = tempEnvironment37
arcpy.env.mask = tempEnvironment38
arcpy.env.spatialGrid3 = tempEnvironment39
arcpy.env.maintainSpatialIndex = tempEnvironment40
arcpy.env.workspace = tempEnvironment41
arcpy.env.MResolution = tempEnvironment42
arcpy.env.derivedPrecision = tempEnvironment43
arcpy.env.ZTolerance = tempEnvironment44

# Process: Table Select
arcpy.TableSelect_analysis(Output_Table, PSA_List_TableSelect, "\"CITY\" is not null AND \"CITY\" <> 'DISTRICT'")
print "Table Select Complete"

# Process: Add Field
arcpy.AddField_management(PSA_List_TableSelect, "TYPE", "TEXT", "", "", "25", "", "NULLABLE", "NON_REQUIRED", "")
print "Add Field Complete"

# Process: Calculate Field
arcpy.CalculateField_management(PSA_List_TableSelect__5_, "TYPE", "x", "VB", "Dim x\\nIf InStr( [NAME], \"*\"  ) then\\nx = \"RD\"\\nElseIf InStr( [CITY], \"Current Ops Chief\"  ) then\\nx = \"Current Ops Chief\"\\nElseIf InStr( [CITY], \"Section Chief\"  ) then\\nx = \"Section Chief\"\\nElseIf InStr( [CITY], \"Branch Chief\"  ) then\\nx = \"*Branch Chief\"\\nElseIf InStr( [CITY], \"Headquarters\"  ) then\\nx = \"PSA\"\\nElse\\nx=\"PSA\"\\nEnd If")

# Process: Calculate Field (2)
arcpy.CalculateField_management(PSA_List_TableSelect, "CITY", "x", "VB", "Dim x\\nIf InStr( [CITY], \"Current Ops Chief\"  ) then\\nx = \"Arlington\"\\nElseIf InStr( [CITY], \"Section Chief\"  ) then\\nx = \"Arlington\"\\nElseIf InStr( [CITY], \"Branch Chief\"  ) then\\nx = \"Arlington\"\\nElseIf InStr( [CITY], \"Headquarters\"  ) then\\nx = \"Arlington\"\\nElse x=[CITY]\\nEnd If")

# Process: Calculate Field (3)
arcpy.CalculateField_management(PSA_List_TableSelect, "STATE", "x", "VB", "Dim x\\nIf InStr( [CITY], \"Arlington\"  ) then\\nx = \"VA\"\\nElse x=[STATE]\\nEnd If")

# Process: Calculate Field (5)
arcpy.CalculateField_management(PSA_List_TableSelect, "CITY", "x", "VB", "Dim x\\nIf InStr( [CITY], \"New York City\"  ) then\\nx = \"New York\"\\nElse x=[CITY]\\nEnd If")
print "Calculate Field Complete"

# Process: Geocode Addresses
arcpy.GeocodeAddresses_geocoding(PSA_List_TableSelect, Navteq_Cities_Composite, "City City VISIBLE NONE;State State VISIBLE NONE;Country <None> VISIBLE NONE", PSAs_and_RDs, "STATIC")
print "Geocoding Complete"

# Process: Spatial Join
arcpy.SpatialJoin_analysis(PSAs_and_RDs, FEMA_Regions_WGS84_Tribal_Overlap_Clip_20130402, PSAs_and_RDs_SpatialJoin, "JOIN_ONE_TO_ONE", "KEEP_ALL", "NAME \"NAME\" true true false 255 Text 0 0 ,First,#,D:\\Users\\Products\\PSA Map Updates\\Automation\\Data\\Features.gdb\\PSAs_and_RDs,NAME,-1,-1;CITY \"CITY\" true true false 255 Text 0 0 ,First,#,D:\\Users\\Products\\PSA Map Updates\\Automation\\Data\\Features.gdb\\PSAs_and_RDs,CITY,-1,-1;STATE \"STATE\" true true false 255 Text 0 0 ,First,#,D:\\Users\\Products\\PSA Map Updates\\Automation\\Data\\Features.gdb\\PSAs_and_RDs,STATE,-1,-1;TYPE \"TYPE\" true true false 30 Text 0 0 ,First,#,D:\\Users\\Products\\PSA Map Updates\\Automation\\Data\\Features.gdb\\PSAs_and_RDs,TYPE,-1,-1;REGION \"REGION\" true true false 254 Text 0 0 ,First,#,D:\\Users\\Products\\PSA Map Updates\\Data\\Updates_20130401\\Regions and Districts Modified by Tribal.gdb\\FEMA_Regions_WGS84_Tribal_Overlap_Clip_20130402,REGION,-1,-1", "INTERSECT", "", "")
#arcpy.SpatialJoin_analysis(PSAs_and_RDs, FEMA_Regions_WGS84_Tribal_Overlap_Clip_20130402, PSAs_and_RDs_SpatialJoin, "JOIN_ONE_TO_ONE", "KEEP_ALL", "NAME \"NAME\" true true false 255 Text 0 0 ,First,#,D:\Users\Products\PSA Map Updates\Automation\for ESRI Presentation\Data\Features.gdb\\PSAs_and_RDs,NAME,-1,-1;CITY \"CITY\" true true false 255 Text 0 0 ,First,#,D:\Users\Products\PSA Map Updates\Automation\for ESRI Presentation\Data\Features.gdb\\PSAs_and_RDs,CITY,-1,-1;STATE \"STATE\" true true false 255 Text 0 0 ,First,#,D:\Users\Products\PSA Map Updates\Automation\for ESRI Presentation\Data\Features.gdb\\PSAs_and_RDs,STATE,-1,-1;PHONE_OFFICE \"PHONE_OFFICE\" true true false 255 Text 0 0 ,First,#,D:\Users\Products\PSA Map Updates\Automation\for ESRI Presentation\Data\Features.gdb\\PSAs_and_RDs,PHONE_OFFICE,-1,-1;PHONE_MOBILE \"PHONE_MOBILE\" true true false 255 Text 0 0 ,First,#,D:\Users\Products\PSA Map Updates\Automation\for ESRI Presentation\Data\Features.gdb\\PSAs_and_RDs,PHONE_MOBILE,-1,-1;EMAIL \"EMAIL\" true true false 255 Text 0 0 ,First,#,D:\Users\Products\PSA Map Updates\Automation\for ESRI Presentation\Data\Features.gdb\\PSAs_and_RDs,EMAIL,-1,-1;TYPE \"TYPE\" true true false 30 Text 0 0 ,First,#,D:\Users\Products\PSA Map Updates\Automation\for ESRI Presentation\Data\Features.gdb\\PSAs_and_RDs,TYPE,-1,-1;REGION \"REGION\" true true false 254 Text 0 0 ,First,#,D:\Users\Products\PSA Map Updates\Automation\for ESRI Presentation\Data\Features.gdb\\FEMA_Regions_WGS84_Tribal_Overlap_Clip_20130402,REGION,-1,-1", "INTERSECT", "", "")
print "Spatial Join to Define Regions Complete"

# Process: Calculate Field (6)
arcpy.CalculateField_management(PSAs_and_RDs_SpatialJoin, "NAME", "Replace( [NAME], \"*\", \"\" )", "VB", "")
print "Calculate Field Complete"

# Process: Calculate Field (7)
arcpy.CalculateField_management(PSAs_and_RDs_SpatialJoin__4_, "REGION", "x", "VB", "Dim x\\nIf InStr( [CITY], \"Arlington\"  ) then\\nx = \"Headquarters\"\\nElse x=[REGION]\\nEnd If")
print "Calculate Field Complete"

# Process: Calculate Field (8)
arcpy.CalculateField_management(PSAs_and_RDs_SpatialJoin__4_, "STATE", "x", "VB", "Dim x\\nIf InStr( [CITY], \"Washington\"  ) then\\nx = \"DC\"\\nElse x=[STATE]\\nEnd If")
print "Calculate Field Complete"

# Process: Delete Field
arcpy.DeleteField_management(PSAs_and_RDs_SpatialJoin__2_, "Join_Count;TARGET_FID")
print "Delete Field Complete"

print "PSA/RD Spatial Transition Completed"

#####################11x17 Update##############################

strArcMapPath = r"C:\Program Files (x86)\ArcGIS\Desktop10.1\bin\ArcMap.exe"
strMxd = r"D:\Users\Products\PSA Map Updates\Automation\for ESRI Presentation\MXDs\Personnel Location Map - 11x17 - Final.mxd"

objNewProcess = subprocess.Popen([strArcMapPath, strMxd])
#objNewProcess.wait() # this line will wait for the new process to end

### Timestamp the PDF
##datetime = datetime.datetime.now().strftime("%Y-%m-%d-%H%M")
##timestamped_out_pdf = timestamped_out_pdf_dir + datetime +'.pdf'
##print timestamped_out_pdf
##localPDF = os.rename(out_pdf, timestamped_out_pdf)


##os.system('taskkill /IM Arcmap*')

OutputPDF_11x17 = r"D:\Users\PrintToPDF_Swapspace\Map Document.pdf"
RenamedOutputPDF_11x17 = r"D:\Users\PrintToPDF_Swapspace\PSA Location Map 11x17.pdf"

try:
    os.remove(RenamedOutputPDF_11x17)
    print "Old OutputPDF 11x17 file Removed"
except:
    pass

print "Waiting 90 Seconds for 11x17 file generation"
time.sleep(90)

        
try:
    os.rename(OutputPDF_11x17, RenamedOutputPDF_11x17)
    print "Renamed 11x17 File"
except:
    pass

os.system('taskkill /IM Arcmap*')
print "ArcMap Terminated"


print "PSA Location Map Update Process Complete"





